config/routes.rb
Rails.application.routes.draw do
  # Calendar
  get 'calendar(/:month/:year)' => 'calendars#show', :as => :calendar
  resources :calendar_events, only: [:index, :show], path: '/events'

  namespace :admin do
    resources :calendar_events, except: [:index]
    resources :calendars, except: [:index]
    get 'events(/:month(/:year(/:calendar)))' => 'calendar_events#index', :as => 'list_spud_calendar_events'
  end
end

app/controllers/admin/calendar_events_controller.rb
class Admin::CalendarEventsController < Admin::ApplicationController
  add_breadcrumb 'Events', :admin_list_spud_calendar_events_path
  belongs_to_app :events

  respond_to :html, :xml, :json
  respond_to :js, only: [:index]

  def index
    if params[:month]
      year = params[:year] ? params[:year].to_i : Date.today.year
      begin
        @calendar_date = Date.new(year, params[:month].to_i)
      rescue
        @calendar_date = Date.today
      end
    else
      @calendar_date = Date.today
    end

    if params[:spud_calendar] && calendar = SpudCalendar.find_by_title(params[:spud_calendar].titleize)
      @calendar_events = calendar.events
    else
      @calendar_events = SpudCalendarEvent
    end
    @calendar_events = @calendar_events.in_month_of(@calendar_date).order('spud_calendar_events.start_at ASC').to_a

    @calendars = SpudCalendar.all
    @current_calendar = params[:spud_calendar] ? params[:spud_calendar] : 0

    respond_with(@calendars, include: :events)
  end

  def new
    @calendar_event = SpudCalendarEvent.new
    if params[:spud_calendar]
      @calendar_event.spud_calendar_id = SpudCalendar.find_by_title(params[:spud_calendar].titleize).id
    end
  end

  def edit
    @calendar_event = SpudCalendarEvent.find(params[:id])
  end

  def create
    @calendar_event = SpudCalendarEvent.new(calendar_event_params)
    flash[:notice] = 'Calendar event was successfully created.' if @calendar_event.save
    respond_with(@calendar_event, location: admin_list_spud_calendar_events_path)
  end

  def update
    @calendar_event = SpudCalendarEvent.find(params[:id])
    flash[:notice] = 'Calendar event was successfully updated.' if @calendar_event.update_attributes(calendar_event_params)
    respond_with(@calendar_event, location: admin_list_spud_calendar_events_path)
  end

  def destroy
    @calendar_event = SpudCalendarEvent.find(params[:id])
    flash[:notice] = 'Calendar event deleted successfully' if @calendar_event.destroy
    respond_with(@calendar_event, location: admin_list_spud_calendar_events_path)
  end

  private

  def calendar_event_params
    params.require(:spud_calendar_event).permit(:title, :description, :start_at, :end_at, :all_day, :spud_calendar_id, :spud_calendar, :location, :address, :address_2, :city, :state, :zip)
  end
end

app/controllers/calendar_events_controller.rb
class CalendarEventsController < ApplicationController
  respond_to :html, :json
  layout SpudEvents.config.calendar_layout

  def index
    @events = SpudCalendarEvent.ordered.paginate(per_page: 10, page: params[:page])
    respond_with @events
  end

  def show
    @event = SpudCalendarEvent.find(params[:id])
    respond_with @event
  end
end

app/helpers/admin/calendar_events_helper.rb
module Admin::CalendarEventsHelper
end

app/views/admin/calendar_events/_calendar.html.erb
<%= link_to_next_admin_calendar_month @calendar_date %>
<%= link_to_previous_admin_calendar_month @calendar_date %>

<%= spud_calendar_for_events(@calendar_events, @calendar_date, :headers => ['S', 'M', 'T', 'W', 'T', 'F', 'S']) do |day, events| %>
  <span class="calendar-day">
    <%= day.day %>
  </span>
  <ul class="calendar-events-list">
    <% events.each do |event| %>
      <li>
        <%= link_to edit_admin_calendar_event_path(event.id) do %>
          <span class="label" style="background-color: #<%= event.spud_calendar.color %>">
            <%= truncate(event.title, :length => 25) %>
          </span>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/admin/calendar_events/_form.html.erb
<%= form_for @calendar_event, :url => path, :builder => TbCore::FormBuilder, :html => {:class => "form-horizontal"} do |f| %>
  <%= tb_form_error_header(f.object) %>

  <%= f.tb_select :spud_calendar_id, options_from_collection_for_select(SpudCalendar.all, :id, :title, @calendar_event.spud_calendar_id) %>

  <%= f.tb_text_field :title %>
  <%= f.tb_text_area :description, :style => "width:100%;", :class => 'tinymce full-width' %>
  
  <%= f.tb_datetime_select :start_at, :ampm => true, :minute_step => 5 %>
  <%= f.tb_datetime_select :end_at, :ampm => true, :minute_step => 5 %>

  <%= f.tb_text_field :location %>
  <%= f.tb_text_field :address %>
  <%= f.tb_text_field :address_2 %>
  <%= f.tb_text_field :city %>
  <%= f.tb_text_field :state %>
  <%= f.tb_text_field :zip %>

  <%= f.tb_save_buttons 'Event', admin_list_spud_calendar_events_path, @calendar_event.id ? admin_calendar_event_path(@calendar_event) : nil %>

<% end %>

app/views/admin/calendar_events/edit.html.erb
<%= render :partial => 'form', :locals => {:path => admin_calendar_event_path(@calendar_event)} %>

app/views/admin/calendar_events/index.html.erb
<% @page_name = "Events - #{@calendar_date.strftime('%B %Y')}" %>

<%= content_for :data_controls do %>
  <%= link_to "New Calendar", new_admin_calendar_path, :class => "btn btn-default" %>
  <%= link_to "New Event", new_admin_calendar_event_path, :class => "btn btn-primary" %>
<% end %>

<%= content_for :detail do %>

  <div class="row">
    <div id="spud_events_admin_calendar" class="col-md-8">
      <%= render :partial => 'calendar' %>
    </div>

    <div class="col-md-4">
      <ul id="spud_events_admin_calendar_legend">
        <%= render :partial => 'admin/calendars/calendar_legend', :collection => @calendars, :as => :calendar %>
      </ul>
    </div>
  </div>

  <script>
    $(document).ready(function() {
      spud.admin.events.init();
    });
  </script>

<% end %>

app/views/admin/calendar_events/new.html.erb
<%= render :partial => 'form', :locals => {:path => admin_calendar_events_path} %>